name: 📊 Daily AdMob Network → BigQuery Export

on:
  schedule:
    - cron: '0 2 * * *'     # runs automatically at 01:00 UTC
  workflow_dispatch:        # still allows manual runs with inputs
    inputs:
      run_date:
        description: 'Date for report (YYYY-MM-DD)'
        required: false    # optional

jobs:
  export:
    runs-on: ubuntu-latest

    env:
      REPORT_DATE:          ${{ github.event.inputs.run_date }}
      ADMOB_CLIENT_ID:      ${{ secrets.ADMOB_CLIENT_ID }}
      ADMOB_CLIENT_SECRET:  ${{ secrets.ADMOB_CLIENT_SECRET }}
      ADMOB_REFRESH_TOKEN:  ${{ secrets.ADMOB_REFRESH_TOKEN }}
      ADMOB_PUBLISHER_ID:   ${{ secrets.ADMOB_PUBLISHER_ID }}
      APP1:                 ${{ secrets.APP1 }}
      APP2:                 ${{ secrets.APP2 }}

      GCP_PROJECT:          ${{ secrets.GCP_PROJECT }}
      GCS_BUCKET_NAME:      ${{ secrets.GCS_BUCKET_NAME }}
      BQ_DATASET:           ${{ secrets.BQ_DATASET }}
      BQ_TABLE_NETWORK:     ${{ secrets.BQ_TABLE_NETWORK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP (GCS & BigQuery)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dump environment variables
        run: |
          echo "=== ENVIRONMENT DUMP ==="
          env

      - name: Check ADMOB_PUBLISHER_ID
        run: |
          echo "ADMOB_PUBLISHER_ID='$ADMOB_PUBLISHER_ID'"
          if [ -z "$ADMOB_PUBLISHER_ID" ]; then
            echo "❌ ERROR: ADMOB_PUBLISHER_ID is empty or not set!"
            exit 1
          fi

      - name: Run Network Report pipeline
        run: python save_network_CSV.py
