name: 📊 AdMob Network → BigQuery + Native CTR Alerts

on:
  schedule:
    # Runs five times per day at 00:00, 05:00, 10:00, 15:00, 20:00 UTC
    - cron: '0 0,5,10,15,20 * * *'
  workflow_dispatch:
    inputs:
      run_date:
        description: 'Date for report (YYYY-MM-DD)'
        required: false

jobs:
  fetch-and-alert:
    runs-on: ubuntu-latest

    env:
      REPORT_DATE:          ${{ github.event.inputs.run_date }}
      ADMOB_CLIENT_ID:      ${{ secrets.ADMOB_CLIENT_ID }}
      ADMOB_CLIENT_SECRET:  ${{ secrets.ADMOB_CLIENT_SECRET }}
      ADMOB_REFRESH_TOKEN:  ${{ secrets.ADMOB_REFRESH_TOKEN }}
      ADMOB_PUBLISHER_ID:   ${{ secrets.ADMOB_PUBLISHER_ID }}
      APP1:                 ${{ secrets.APP1 }}
      APP2:                 ${{ secrets.APP2 }}

      GCP_PROJECT:          ${{ secrets.GCP_PROJECT }}
      GCS_BUCKET_NAME:      ${{ secrets.GCS_BUCKET_NAME }}
      BQ_DATASET:           ${{ secrets.BQ_DATASET }}
      BQ_TABLE_NETWORK:     ${{ secrets.BQ_TABLE_NETWORK }}
      SLACK_WEBHOOK_URL:    ${{ secrets.SLACK_WEBHOOK_URL }}
      AD_UNIT_ID:           ${{ secrets.AD_UNIT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP (for GCS & BigQuery)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dump environment variables
        run: |
          echo "=== ENVIRONMENT DUMP ==="
          env

      - name: Check required env vars
        run: |
          for var in ADMOB_PUBLISHER_ID APP1 APP2 GCP_PROJECT GCS_BUCKET_NAME BQ_DATASET BQ_TABLE_NETWORK SLACK_WEBHOOK_URL AD_UNIT_ID; do
            if [ -z "${!var}" ]; then
              echo "❌ ERROR: $var is empty or not set!"
              exit 1
            fi
          done

      - name: Run Network Report + Native-CTR Alerts
        run: python native_CTR_alerts.py
